"C:\Program Files\MySQL\MySQL Server 5.0\bin\mysql.exe" --user=root -e "source selItemInsertTrg.sql"
"C:\Program Files\MySQL\MySQL Server 5.0\bin\mysql.exe" --user=root -e "source selItemUpdateTrg.sql"
"C:\Program Files\MySQL\MySQL Server 5.0\bin\mysql.exe" --user=root -e "source selItemDeleteTrg.sql"
"C:\Program Files\MySQL\MySQL Server 5.0\bin\mysql.exe" --user=root -e "source entryInsertTrg.sql"
"C:\Program Files\MySQL\MySQL Server 5.0\bin\mysql.exe" --user=root -e "source entryUpdateTrg.sql"
"C:\Program Files\MySQL\MySQL Server 5.0\bin\mysql.exe" --user=root -e "source entryDeleteTrg.sql"